// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfuHEHw2SHiXh3PRa-CosKKRnlyOtwopY',
    appId: '1:867227351932:android:ec3b6e4b33b610d28482f9',
    messagingSenderId: '867227351932',
    projectId: 'getx-gpt',
    storageBucket: 'getx-gpt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBekTCpwmzrjZTvBi-4b3D01K3tPiUowT8',
    appId: '1:867227351932:ios:7808a064eb4e153d8482f9',
    messagingSenderId: '867227351932',
    projectId: 'getx-gpt',
    storageBucket: 'getx-gpt.appspot.com',
    androidClientId: '867227351932-q9j4uk86u2d0qsfmj4o60tahco9rfm4i.apps.googleusercontent.com',
    iosClientId: '867227351932-bvqhlcchhl0cpfduqapl6qdu8i6gtkpo.apps.googleusercontent.com',
    iosBundleId: 'com.devwithjams.getxgptexample',
  );
}
